networks:
  localprom:
    driver: bridge
  db:
    driver: bridge

services:
  app:
    build:
      context: ..
      dockerfile: dev/Dockerfile
    volumes:
      - ..:/app
    environment:
      - ENVIRONMENT=development
      - TZ=Europe/Amsterdam
      - DB_DATABASE=sjb_site
      - DB_USER=user
      - DB_PASSWORD=password
      - DB=db
      - DB_PORT=3306
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "80:4000"
      - "9091:9091"
    networks:
      - localprom
      - db
    tty: true

  db:
    image: mariadb
    container_name: sjb_site_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sjb_site
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./database:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - db
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]
      start_period: 5s
      timeout: 5s
      retries: 50

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - 3333:80
    networks:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORT: password

  prometheus:
    image: prom/prometheus
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    networks:
      - localprom
    ports:
      - 9090:9090
