services:
  app:
    volumes:
      - ..:/app
    environment:
      - ENVIRONMENT=development
      - TZ=Europe/Amsterdam
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "4000:4000"

  db:
    image: mariadb
    container_name: sjb_site_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sjb_site
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./database:/var/lib/mysql
    ports:
      - 3306:3306
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]
      start_period: 5s
      timeout: 5s
      retries: 50

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - 3333:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORT: password
