services:
  app:
    build:
      context: ..
      dockerfile: dev/Dockerfile
    volumes:
      - ..:/app
    environment:
      - ENVIRONMENT=development
      - TZ=Europe/Amsterdam
      - DB_DATABASE=sjb_site
      - DB_USER=user
      - DB_PASSWORD=password
      - DB=db
      - DB_PORT=3306
    ports:
      - "4000:4000"
    tty: true
